library(teal)
library(haven)
library(teal.data)
library(teal.modules.general)
library(teal.modules.clinical)
options(shiny.useragg = FALSE)
## App header and footer ----
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
app_source <- "https://github.com/insightsengineering/teal.gallery/tree/main/safety"
gh_issues_page <- "https://github.com/insightsengineering/teal.gallery/issues"

header <- tags$span(
  style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
  tags$span("My first teal app", style = "font-size: 30px;"),
  tags$span(
    style = "display: flex; align-items: center;",
    tags$img(src = nest_logo, alt = "NEST logo", height = "45px", style = "margin-right:10px;"),
    tags$span(style = "font-size: 24px;", "NEST @ Roche")
  )
)

footer <- tags$p(
  "This teal app is brought to you by the NEST Team at Roche/Genentech.
        For more information, please visit:",
  tags$a(href = app_source, target = "_blank", "Source Code"), ", ",
  tags$a(href = gh_issues_page, target = "_blank", "Report Issues")
)
app <- init(
  data = teal_data_module(
    ui = function(id) {
      ns <- NS(id)
      fluidPage(
        mainPanel(
          shiny::fileInput(ns("file"), "Upload a file", multiple = TRUE),
          actionButton(ns("submit"), "Submit"),
          DT::dataTableOutput(ns("preview"))
        )
      )
    },
    server = function(id) {
      moduleServer(id, function(input, output, session) {
        
        data <- eventReactive(input$submit, {
          req(input$file)
          data_list <<- lapply(input$file$datapath, read_sas)

          my_data_vec <- c()
          for(i in seq_along(data_list)) {
            assign(paste0("my_data", i), data_list[[i]], envir = .GlobalEnv)
            my_data_name <- paste0("my_my_data", i)
            my_data_vec <- c(my_data_vec, my_data_name)
          }
          
          td <- within(teal_data(), {
            data_names <- ls(.GlobalEnv, pattern = "^my_data")
            for (name in data_names) {
              assign(paste0("my_", name), get(name, envir = .GlobalEnv))
            }
            rm(my_my_data_name)
            rm(my_my_data_vec)
            rm(name)
            rm(data_names)
          })
          datanames(td) <- my_data_vec
          td

        })
        
        data
      })
    }
  ),
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c("Info about input data source" = "This app uses CDISC ADaM datasets randomly generated by `random.cdisc.data` R packages"),
      tables = list(`NEST packages used in this demo app` = data.frame(
        Packages = c(
          "teal.modules.general",
          "teal.modules.clinical",
          "random.cdisc.data"
        )
      ))
    ),
    tm_data_table("Data Table"),
    tm_variable_browser("Variable Browser")
    
    
  )
  
)

shinyApp(app$ui, app$server)
